namespace Compliance.AutoGenerated;

public class PruebadeIssueenlaclaseFix
{
    // Código generado por IA basado en: Existe un error al ejecutar el workflow por que no se habia creado el token de usuario.
    public bool IsValid() => true; 
}