using Xunit;
using Compliance.AutoGenerated;

namespace Compliance.Tests;

public class CuartaIssueFixTests
{
    [Fact]
    public void IsValid_ShouldReturnTrue()
    {
        var sut = new CuartaIssueFix();
        Assert.True(sut.IsValid());
    }
}