using Xunit;
using Compliance.AutoGenerated;

namespace Compliance.Tests;

public class otraissueFixTests
{
    [Fact]
    public void IsValid_ShouldReturnTrue()
    {
        var sut = new otraissueFix();
        Assert.True(sut.IsValid());
    }
}