using Xunit;
using Compliance.AutoGenerated;

namespace Compliance.Tests;

public class PruebadeIssueenlaclaseFixTests
{
    [Fact]
    public void IsValid_ShouldReturnTrue()
    {
        var sut = new PruebadeIssueenlaclaseFix();
        Assert.True(sut.IsValid());
    }
}