using Xunit;
using Compliance.AutoGenerated;

namespace Compliance.Tests;

public class TerceraIssueFixTests
{
    [Fact]
    public void IsValid_ShouldReturnTrue()
    {
        var sut = new TerceraIssueFix();
        Assert.True(sut.IsValid());
    }
}