using System.Text.Json;

namespace AiSquad.Cli;

class Program
{
    static async Task Main(string[] args)
    {
        Console.WriteLine("AiSquad.Cli Iniciado...");

        // 1. Recibir los parámetros desde GitHub Actions
        if (args.Length < 2)
        {
            Console.WriteLine("Error: Faltan argumentos. Uso: AiSquad.Cli <IssueTitle> <IssueBody>");
            return;
        }

        string issueTitle = args[0];
        string issueBody = args[1];

        Console.WriteLine($"Analizando Issue: {issueTitle}");

        // 2. Aquí iría la llamada real a la API de OpenAI (Ej: Semantic Kernel)
        // Para este laboratorio, simularemos que la IA generó este código base
        var (codigoGenerado, pruebaGenerada) = SimularLlamadaInteligenciaArtificial(issueTitle, issueBody);

        // 3. Crear los archivos físicos en el repositorio
        // Asumimos que GitHub Actions ejecutará esto desde la raíz del repo
        string sourceFolder = "src/AutoGenerated";
        string testFolder = "tests/AutoGenerated.Tests";

        Directory.CreateDirectory(sourceFolder);
        Directory.CreateDirectory(testFolder);

        string className = issueTitle.Replace(" ", "").Replace("Bug", "") + "Fix";

        await File.WriteAllTextAsync($"{sourceFolder}/{className}.cs", codigoGenerado);
        await File.WriteAllTextAsync($"{testFolder}/{className}Tests.cs", pruebaGenerada);

        Console.WriteLine("✅ Código y Pruebas generados exitosamente. Archivos guardados.");
    }

    // Método que simula el motor de IA
    static (string code, string test) SimularLlamadaInteligenciaArtificial(string titulo, string body)
    {
        string className = titulo.Replace(" ", "").Replace("Bug", "") + "Fix";

        string code = $$"""
        namespace Compliance.AutoGenerated;
        
        public class {{className}}
        {
            // Código generado por IA basado en: {{body}}
            public bool IsValid() => true; 
        }
        """;

        string test = $$"""
        using Xunit;
        using Compliance.AutoGenerated;

        namespace Compliance.Tests;

        public class {{className}}Tests
        {
            [Fact]
            public void IsValid_ShouldReturnTrue()
            {
                var sut = new {{className}}();
                Assert.True(sut.IsValid());
            }
        }
        """;

        return (code, test);
    }
}
